services:
  postgres:
    image: postgres:13.21-alpine3.21
    network_mode: "host"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app_veterinaria
    ports:
      - "5432:5432"
    volumes:
      - "/home/manuel/HDD/proyectos/vaterinarias/data:/var/lib/postgresql/data"